# Generated by Django 4.1.3 on 2022-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_image_review_customuser_listings_userreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile_image',
            field=models.URLField(),
        ),
    ]
