# Generated by Django 4.1.3 on 2022-12-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_image_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address_line_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='US', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip_code',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(501), django.core.validators.MaxValueValidator(99950)]),
        ),
    ]
