# Generated by Django 4.1.3 on 2022-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_listing_service_userlisting_listingservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='description pending', max_length=255, unique=True),
        ),
    ]
