# Generated by Django 4.1.3 on 2022-11-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='description pending', max_length=255),
        ),
    ]
