# Generated by Django 4.1.3 on 2022-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='service',
            field=models.ManyToManyField(related_name='listings', through='plants.ListingService', to='plants.service'),
        ),
    ]
