# Generated by Django 4.1.3 on 2022-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
