# Generated by Django 4.1.3 on 2022-12-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='heading',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
