# Generated by Django 4.1.3 on 2022-12-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_listing_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='heading',
            field=models.CharField(default='Certified Caregiver', max_length=50),
        ),
    ]
