# Generated by Django 4.1.3 on 2022-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_alter_listing_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.URLField(null=True),
        ),
    ]
